/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ImpitError extends Error {}
export declare class HTTPError extends ImpitError {}
export declare class RequestError extends ImpitError {}
export declare class TransportError extends RequestError {}
export declare class TimeoutError extends TransportError {}
export declare class ConnectTimeout extends TimeoutError {}
export declare class ReadTimeout extends TimeoutError {}
export declare class WriteTimeout extends TimeoutError {}
export declare class PoolTimeout extends TimeoutError {}
export declare class NetworkError extends TransportError {}
export declare class ConnectError extends NetworkError {}
export declare class ReadError extends NetworkError {}
export declare class WriteError extends NetworkError {}
export declare class CloseError extends NetworkError {}
export declare class ProtocolError extends TransportError {}
export declare class LocalProtocolError extends ProtocolError {}
export declare class RemoteProtocolError extends ProtocolError {}
export declare class ProxyError extends TransportError {}
export declare class ProxyTunnelError extends ProxyError {
  status?: number
}
export declare class ProxyAuthRequired extends ProxyError {}
export declare class UnsupportedProtocol extends TransportError {}
export declare class DecodingError extends RequestError {}
export declare class TooManyRedirects extends RequestError {}
export declare class HTTPStatusError extends HTTPError {}
export declare class InvalidURL extends ImpitError {}
export declare class CookieConflict extends ImpitError {}
export declare class StreamError extends ImpitError {}
export declare class StreamConsumed extends StreamError {}
export declare class ResponseNotRead extends StreamError {}
export declare class RequestNotRead extends StreamError {}
export declare class StreamClosed extends StreamError {}

export interface RequestInit {
  /**
   * The redirect mode to use for this request.
   *
   * - `'follow'` (default): Follow redirects automatically.
   * - `'manual'`: Do not follow redirects; return the 3xx response as-is.
   * - `'error'`: Throw a `TypeError` if the response is a redirect.
   *
   * When set, this overrides the instance-level {@link ImpitOptions.followRedirects} option for this request.
   *
   * @see {@link https://developer.mozilla.org/en-US/docs/Web/API/RequestInit/redirect | Fetch API `redirect` option}
   */
  redirect?: 'follow' | 'manual' | 'error'
}
