name: "[impit-python] Run code checks"

on:
  workflow_dispatch: null
  workflow_call:

permissions:
  contents: read

jobs:
  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Set up uv package manager
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Disable automatic `uv` builds
        run: sed -i '/^\[tool\.uv\]$/a package = false' pyproject.toml
        working-directory: impit-python

      - name: Install Python dependencies
        run: uv sync --all-extras --frozen
        working-directory: impit-python

      - name: Run lint check
        run: uv run ruff format --diff --check && uv run ruff check --diff
        working-directory: impit-python

  type_check:
    name: Type check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Set up uv package manager
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Disable automatic `uv` builds
        run: sed -i '/^\[tool\.uv\]$/a package = false' pyproject.toml
        working-directory: impit-python

      - name: Install Python dependencies
        run: uv sync --all-extras --frozen
        working-directory: impit-python

      - name: Run type check
        run: uv run mypy
        working-directory: impit-python
